apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: dquyen2806/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"